apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-blue
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice
      version: v1
  template:
    metadata:
      labels:
        app: microservice
        version: v1
    spec:
      containers:
        - name: microservice-blue
          image: sowmiyahemanth/microservice-blue:v1
          ports:
            - containerPort: 3000

