apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-green
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice
      version: v2
  template:
    metadata:
      labels:
        app: microservice
        version: v2
    spec:
      containers:
        - name: microservice-green
          image: sowmiyahemanth/microservice-green:v1
          ports:
            - containerPort: 3000

