apiVersion: v1
kind: Service
metadata:
  name: microservice
  namespace: prod
spec:
  type: ClusterIP
  selector:
    app: microservice
    version: v1   # ✅ must match your Deployment pod labels
  ports:
    - port: 80
      targetPort: 3000   # match the port in server.js

