apiVersion: v1
kind: Service
metadata:
  name: microservice
  namespace: prod
spec:
  type: ClusterIP
  selector:
    app: microservice
    version: v1   # 👉 this points to BLUE
  ports:
    - port: 80
      targetPort: 3000
